Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    home,
    movie_detail,
    anime_watching,
    blog,
    categories,
    user_login,
    signup,
    category,
    search,
    suggestmovie,
)

urlpatterns = [
    path("", home, name="home"),
    path("movie_detail/<slug:slug>", movie_detail, name="movie_detail"),
    path("anime-watching/<slug:slug>", anime_watching, name="anime-watching"),
    path("blog/", blog, name="blog"),
    path("category/", category, name="category"),
    path('categories/<slug:slug>/', categories, name='categories'),
    path("login/", user_login, name="login"),
    path('search/', search, name='search'),
    path("signup/", signup, name="signup"),
    path('suggestmovie/', suggestmovie, name='suggestmovie'),
]

core/models.py
from django.db import models
from autoslug import AutoSlugField

class Geners(models.Model):
    title = models.CharField(max_length=30)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title



class MovieCategory(models.TextChoices):
    COMEDY = 'Comedy', 'Comedy'
    DRAMA = 'Drama', 'Drama'
    ACTION = 'Action', 'Action'
    ROMANCE = 'Romance', 'Romance'
    ADVENTURE = 'Adventure', 'Adventure'




class MovieStatus(models.TextChoices):
    TOP_RATED = 'TR', 'Top Rated'
    TRENDING_NOW = 'TN', 'Trending Now'
    MOST_POPULAR = 'MP', 'Most Popular'


class Movie(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=1000, blank=True)
    image = models.ImageField(upload_to='movies/')
    release_date = models.DateField()
    rating = models.DecimalField(default=0, max_digits=3, decimal_places=1)
    views_count = models.IntegerField(default=0)
    status = models.CharField(choices=MovieStatus.choices, max_length=2)
    category = models.CharField(choices=MovieCategory.choices, max_length=10)
    genres = models.ManyToManyField(Geners)
    new_slug = AutoSlugField(populate_from='title', unique=True, null=True, default=None)
    video = models.FileField(upload_to='videos/', null=True, blank=True)

    def __str__(self):
        return self.title


class Banners(models.Model):
    title = models.CharField(max_length=150)
    cover = models.ImageField(upload_to='banners/')
    category = models.CharField(choices=MovieCategory.choices, max_length=100)


    def __str__(self) -> str:
        return self.title


class Side_items(models.Model):
    title = models.CharField(max_length=150)
    picture = models.ImageField(upload_to='Side-Pics/')
    rating = models.DecimalField(default=0, max_digits=3, decimal_places=1)

    
    def __str__(self) -> str:
        return self.title

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Banners, Side_items, Geners
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
import random

def home(request):
    banners = Banners.objects.all()
    most_popular = Movie.objects.filter(status="MP")
    trending_now = Movie.objects.filter(status="TN")
    top_rated = Movie.objects.filter(status="TR")
    side_items = Side_items.objects.all()

    context = {
        "most_popular": most_popular,
        "trending_now": trending_now,
        "banners": banners,
        "side_items": side_items,
        "top_rated": top_rated,
    }
    return render(request, "index.html", context)

def movie_detail(request, slug):
    movie = get_object_or_404(Movie, new_slug=slug)
    side_items = Side_items.objects.all()
    context = {
        "movie": movie,
        "side_items": side_items,
    }
    return render(request, "anime-details.html", context)

def suggestmovie(request):
    all_movies = list(Movie.objects.all())
    suggested_movies = random.sample(all_movies, min(len(all_movies), 3))  # Adjust the number as needed
    return render(request, 'suggestmovie.html', {'suggested_movies': suggested_movies})

def search(request):
    query = request.GET.get('q')
    if query:
        movies = Movie.objects.filter(title__icontains=query)
        context = {'movies': movies, 'query': query}
        return render(request, 'search_results.html', context)
    else:
        return render(request, 'index.html')

def anime_watching(request, slug):
    movie = get_object_or_404(Movie, new_slug=slug)
    context = {"movie": movie}
    return render(request, "anime-watching.html", context)

def blog(request):
    return render(request, "blog.html")

def categories(request, slug):
    genre = get_object_or_404(Geners, title=slug)
    movies = Movie.objects.filter(genres=genre)
    context = {
        "genre": genre,
        "movies": movies,
    }
    return render(request, "categories.html", context)

def category(request):
    movies = Movie.objects.filter(category="CO")
    context = {"movies": movies}
    return render(request, "categories.html", context)


def user_login(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        if email and password:
            user = authenticate(request, email=email, password=password)
            login(request, user)
            redirect("home")

    return render(request, "login.html")


def signup(request):
    if request.method == "POST":
        email = request.POST.get("email")
        name = request.POST.get("name")
        password = request.POST.get("password")
        if email and password and name:
            user = User.objects.create_user(email, password=password, username=name)
            user.save()
            redirect("home")
    return render(request, "signup.html")

templates/anime-details.html
{% load static %}
{% include 'navbar.html' %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="{% url "home" %}"><i class="fa fa-home"></i> Home</a>
                        <a href="#">categories</a>
                        <span>{{movie.get_category_display}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Anime Section Begin -->
f    <section class="anime-details spad">
        <div class="container">
            <div class="anime__details__content">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="anime__details__pic set-bg" data-setbg="{{movie.image.url}}">
                            <div class="comment"><i class="fa fa-comments"></i></div>
                            <div class="view"><i class="fa fa-eye"></i>{{movie.views_count}}</div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="anime__details__text">
                            <div class="anime__details__title">
                                <h3>{{movie.title}}</h3>
                            </div>
                            <div class="anime__details__rating">
                                <div class="rating">
                                    <a href="#"><i class="fa fa-star"></i></a>
                                    <a href="#"><i class="fa fa-star"></i></a>
                                    <a href="#"><i class="fa fa-star"></i></a>
                                    <a href="#"><i class="fa fa-star"></i></a>
                                    <a href="#"><i class="fa fa-star-half-o"></i></a>
                                </div>
                                <span>1.029 Votes</span>
                            </div>
                            <p>{{movie.description}}</p>
                            <div class="anime__details__widget">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            <li><span>Type:</span> Movies</li>
                                            <li><span>Studios:</span> Unknown</li>
                                            <li><span>Date aired:</span>{{movie.release_date}}</li>
                                            <li><span>Status:</span> {{movie.get_status_display}}</li>
                                            <li><span>Genre:</span>
                                                {% for genre in movie.genres.all %}
                                                    {{ genre.title }}
                                                    {% if not forloop.last %}, {% endif %}
                                                {% endfor %}
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            {% comment %} <li><span>Scores:</span> </li> {% endcomment %}
                                            <li><span>Rating:</span>{{movie.rating}}/10</li>
                                            <li><span>Duration:</span>Full Movie</li>
                                            <li><span>Quality:</span> HD+</li>
                                            <li><span>Views:</span>{{movie.views_count}}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="anime__details__btn">
                                <a href="#" class="follow-btn"><i class="fa fa-heart-o"></i> Follow</a>
                                <a href="{% url "anime-watching" slug=movie.new_slug%}" class="watch-btn"><span>Watch Now</span> <i
                                    class="fa fa-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <div class="anime__details__review">
                            <div class="section-title">
                                <h5>Reviews</h5>

                        <div class="anime__details__form">
                            <div class="section-title">
                                <h5>Your Comment</h5>
                            </div>
                            <form action="#">
                                <textarea placeholder="Your Comment"></textarea>
                                <button type="submit"><i class="fa fa-location-arrow"></i> Review</button>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="anime__details__sidebar">
                            <div class="section-title">
                                <h5>You might like...</h5>
                            </div>
                        {% include "suggestmovie.html" %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Anime Section End -->

        <!-- Footer Section Begin -->
        <footer class="footer">
            <div class="page-up">
                <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="footer__logo">
                            <a href="{% url "home" %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="footer__nav">
                            <ul>
                                <li class="active"><a href="{% url "home" %}">Homepage</a></li>
                                <li><a href="#">categories</a></li>
                                <li><a href="{% url "blog" %}">Our Blog</a></li>
                                <li><a href="#">Contacts</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        

                      </div>
                  </div>
              </div>
          </footer>
          <!-- Footer Section End -->

          <!-- Search model Begin -->
          <div class="search-model">
            <div class="h-100 d-flex align-items-center justify-content-center">
                <div class="search-close-switch"><i class="icon_close"></i></div>
                <form class="search-model-form">
                    <input type="text" id="search-input" placeholder="Search here.....">
                </form>
            </div>
        </div>
        <!-- Search model end -->

        <!-- Js Plugins -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/player.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'js/mixitup.min.js' %}"></script>
        <script src="{% static 'js/jquery.slicknav.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

    </body>

    </html>

templates/anime-watching.html
{% load static %}
{% include 'navbar.html' %}
    <!-- Header End -->

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="{% url 'home' %}"><i class="fa fa-home"></i> Home</a>
                        <a href="#">{{movie.get_category_display}}</a>
                        <span>{{movie.title}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Anime Section Begin -->
    <section class="anime-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="anime__video__player">
                        <video id="player" playsinline controls data-poster="">
                            <source src="{{movie.video.url}}" type="video/mp4" />
                            <!-- Captions are optional -->
                            <track kind="captions" label="English captions" src="{{movie.caption}}" srclang="en" default />
                        </video>
                    </div>
                    <div class="anime__details__episodes">
                        <div class="section-title">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="anime__details__review">
                        <div class="section-title">
                            <h5>Reviews</h5>
                      
      </footer>
      <!-- Footer Section End -->

      <!-- Search model Begin -->
      <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/blog.html
{% load static %}
{% include 'navbar.html' %}
    <!-- Normal Breadcrumb Begin -->
    <section class="normal-breadcrumb set-bg" data-setbg="img/normal-breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>Our Blog</h2>
                        <p>Welcome to the official Anime blog.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Normal Breadcrumb End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3 style="color: #ffffff;">Soon will Update</h3>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="{% url "home" %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                        <ul>
                            <li class="active"><a href="{% url "home" %}">Homepage</a></li>
                            <li><a href="#">categories</a></li>
                            <li><a href="{% url "blog" %}">Our Blog</a></li>
                            <li><a href="#">Contacts</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    

                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/categories.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>pocomovies | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url "home" %}">
                            <img src="{% static 'img/logo.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="{% url "home" %}">Homepage</a></li>
                                <li><a href="#">categories <span class="arrow_carrot-down"></span></a>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'categories' slug='Action' %}">Action</a></li>

                                        <li><a href="{% url 'categories' slug='Adventure' %}">Adventure</a></li>
                                        <li><a href="{% url 'categories' slug='Darama' %}">Darama</a></li>
                                        <li><a href="{% url 'categories' slug='Comedy' %}">Comedy</a></li>
                                        <li><a href="{% url 'categories' slug='Romance' %}">Romance</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url "blog" %}">Our Blog</a></li>
                                <li><a href="#">Contacts</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="#" class="search-switch"><span class="icon_search"></span></a>
                        <a href="./login.html"><span class="icon_profile"></span></a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="{% url "home" %}"><i class="fa fa-home"></i> Home</a>
                        <a href="#">categories</a>
                        <span>{{category}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Product Section Begin -->
    <section class="product-page spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="product__page__content">
                        <div class="product__page__title">
                            <div class="row">
                                <div class="col-lg-8 col-md-8 col-sm-6">
                                    <div class="section-title">
                                        <h4>{{category}}</h4>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-6">
                                    <div class="product__page__filter">
                                        <p>Order by:</p>
                                        <select>
                                            <option value="">A-Z</option>
                                            <option value="">1-10</option>
                                            <option value="">10-50</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">




                            {% for movie in movies %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product__item">
                                    <div class="product__item__pic set-bg" data-setbg="{{ movie.image.url }}">
                                        <!-- Movie details like episode, comments, views -->
                                    </div>
                                    <div class="product__item__text">
                                        <ul>
                                            <!-- Movie status and type -->
                                        </ul>
                                        <h5><a href="#">{{ movie.title }}</a></h5>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            
                            
                            
                        </div>
                    </div>
                    <div class="product__pagination">
                        <a href="#" class="current-page">1</a>
                        <a href="#">2</a>
                        <a href="#">3</a>
                        <a href="#">4</a>
                        <a href="#">5</a>
                        <a href="#"><i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-8">
                    <div class="product__sidebar">
                        <div class="product__sidebar__view">
                            <div class="section-title">
                                <h5>Top Views</h5>
                            </div>
                            <ul class="filter__controls">
                                <li class="active" data-filter="*">Day</li>
                                <li data-filter=".week">Week</li>
                                <li data-filter=".month">Month</li>
                                <li data-filter=".years">Years</li>
                            </ul>
                            {% for side_item in side_items %}
                            <div class="filter__gallery">
                                <div class="product__sidebar__view__item set-bg mix day years"
                                data-setbg={{ side_item.picture.url }}>
                                <div class="ep">{{side_item.rating}} / 10</div>
                                <div class="view"><i class="fa fa-eye"></i>{{movie.views_count}}</div>
                                <h5><a href="#">{{side_item.title}}</a></h5>
                            </div>
                            {% endfor %}
                            
        </div>
    </div>
    
</div>
</div>
</div>
</div>
</section>
<!-- Product Section End -->

<!-- Footer Section Begin -->
<footer class="footer">
    <div class="page-up">
        <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer__logo">
                    <a href="{% url "home" %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="footer__nav">
                    <ul>
                        <li class="active"><a href="{% url "home" %}">Homepage</a></li>
                        <li><a href="#">categories</a></li>
                        <li><a href="{% url "blog" %}">Our Blog</a></li>
                        <li><a href="#">Contacts</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                

              </div>
          </div>
      </div>
  </footer>
  <!-- Footer Section End -->

  <!-- Search model Begin -->
  <div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search model end -->

<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/player.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/contacts.html
<div class="col-lg-2">
    <div class="header__right">

templates/search_results.html
<h1>Search Results for "{{ query }}"</h1>

{% if movies %}
  <ul>
    {% for movie in movies %}
      <li><a href="{% url 'movie_detail' movie.new_slug %}">{{ movie.title }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No results found.</p>
{% endif %}

templates/suggestmovie.html
{% load static %}
{% for movie in suggested_movies %}
<div class="col-lg-4 col-md-6 col-sm-6">
    <div class="product__item">
        <div class="product__item__pic set-bg" data-setbg="{{ movie.image.url }}">
            <div class="ep">{{ movie.rating }} / 10</div>
            <div class="view"><i class="fa fa-eye"></i>{{ movie.views_count }}</div>
        </div>
        <div class="product__item__text">
            <ul>
                {% for genre in movie.genres.all %}
                <li>{{ genre.title }}</li>
                {% endfor %}
            </ul>
            <h5><a href="{% url 'movie_detail' slug=movie.new_slug %}">{{ movie.title }}</a></h5>
        </div>
    </div>
</div>
{% endfor %}